# Generated by Django 2.2.4 on 2019-08-17 17:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronicName', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the electronic', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an electronic type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole market', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('s', 'Sold'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1)),
                ('electronic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Electronic')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='electronic',
            name='electronicType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ElectronicType'),
        ),
        migrations.AddField(
            model_name='electronic',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Producer'),
        ),
    ]
