# Generated by Django 2.2.4 on 2019-08-17 17:49

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.get_image_path),
        ),
    ]
